// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOA1JJqjQXkORx6PTfZdlAFYgZIiwjaik',
    appId: '1:197976471641:web:cc291e5f1161c450f25948',
    messagingSenderId: '197976471641',
    projectId: 'mapapp-af70a',
    authDomain: 'mapapp-af70a.firebaseapp.com',
    storageBucket: 'mapapp-af70a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZdFZUek_npSj367eTuzo0y4OGeB3-j0',
    appId: '1:197976471641:android:a393514e22d8ce35f25948',
    messagingSenderId: '197976471641',
    projectId: 'mapapp-af70a',
    storageBucket: 'mapapp-af70a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBofKisqdGLodluh5R-J2PA4KTHSF77gYc',
    appId: '1:197976471641:ios:9fb560e8e19fccb0f25948',
    messagingSenderId: '197976471641',
    projectId: 'mapapp-af70a',
    storageBucket: 'mapapp-af70a.appspot.com',
    iosClientId: '197976471641-vtpbam4tf4f3j6077q2kk79vf6hhl71f.apps.googleusercontent.com',
    iosBundleId: 'com.example.map',
  );
}
